In [1]:
from main import SpinSystem

c:\Users\lucas\Projects\spherical-model\main.py:1: SyntaxWarning: invalid escape sequence '\s'
  """
c:\Users\lucas\Projects\spherical-model\main.py:67: SyntaxWarning: invalid escape sequence '\s'
  """
c:\Users\lucas\Projects\spherical-model\main.py:79: SyntaxWarning: invalid escape sequence '\s'
  """
c:\Users\lucas\Projects\spherical-model\main.py:136: SyntaxWarning: invalid escape sequence '\s'
  print("Spherical constraint: \sum\sigma_i^2 = N")


In [2]:
model = SpinSystem(100)

In [5]:
model.sigma

<tf.Variable 'Variable:0' shape=(100,) dtype=float32, numpy=
array([-0.4462686 , -0.47049013,  0.53667384,  0.55834424,  0.9102396 ,
        1.5699661 , -0.47210428,  0.0651833 , -0.09728848, -1.3662133 ,
        0.02811925, -0.9732982 , -1.6232266 ,  0.40890318,  0.3907717 ,
        0.26514745, -0.9930978 , -0.4451396 , -1.0082968 ,  0.24123546,
       -0.14682329, -0.49259123, -0.22326615, -0.658425  ,  0.89020014,
        1.9621079 , -0.5699247 , -2.4960742 , -0.08528956,  0.76857567,
        0.937475  , -0.33842862, -0.26430008, -1.5325541 , -0.38010123,
        0.13381164,  2.0531995 , -2.6326313 , -0.3330739 ,  1.1472855 ,
        1.4014267 ,  0.2532736 ,  0.15518352, -1.2600663 , -0.06708571,
       -0.25459307, -0.31617272,  1.2906404 , -1.3209449 , -0.07754658,
       -1.4039611 ,  0.71748996, -0.8985386 ,  0.66239274, -0.38506067,
       -1.623237  , -1.0198898 ,  0.36317343, -0.73306835,  1.7215619 ,
        0.00763746,  1.3218265 ,  1.2911571 ,  0.7385906 ,  0.79556024,
   

In [6]:
model.optimize_energy(learning_rate=0.1, steps=10)

Step 0: Energy = 84.7018


In [7]:
model.sigma

<tf.Variable 'Variable:0' shape=(100,) dtype=float32, numpy=
array([ 0.49055642,  1.1309054 , -0.47974437, -0.8291585 ,  2.076178  ,
        0.3800888 ,  1.0592682 ,  0.07651637,  1.0833303 , -0.03120089,
        0.44049588,  0.27332196,  0.42192772,  0.15500331,  1.6893862 ,
        0.62950146, -1.1989112 , -1.1537867 , -0.43565202,  0.47873378,
       -1.4629096 ,  0.48111242,  1.5867816 , -0.57903117,  2.200066  ,
        0.4160824 , -0.02424751, -1.2441133 , -0.4815842 ,  1.3601791 ,
       -1.2568213 ,  0.24673356,  0.5949032 , -2.074831  ,  0.4886253 ,
       -1.11219   ,  0.47042632,  0.97910273, -1.6517955 ,  0.46545202,
        0.09673204,  0.23322779, -0.92120874, -0.4516865 , -0.21517433,
       -0.56077313,  0.8671516 , -0.32852656, -1.4033163 , -0.96208143,
        0.3956325 ,  1.1901702 , -0.39449427,  0.24485299,  0.30825156,
        1.0004888 , -1.1205114 , -0.24331027,  0.10718234,  0.9327918 ,
        0.33381477,  1.8740946 ,  1.4977788 ,  1.0768988 , -0.19386289,
   

In [8]:
model.J

<tf.Tensor: shape=(100, 100), dtype=float32, numpy=
array([[ 0.        , -0.5842896 ,  0.8340349 , ..., -0.5734232 ,
        -0.5411381 ,  0.07277147],
       [-0.5842896 ,  0.        , -0.05456454, ..., -0.39805448,
         0.2716505 , -0.6077318 ],
       [ 0.8340349 , -0.05456454,  0.        , ..., -0.678915  ,
        -0.9306036 ,  0.5516921 ],
       ...,
       [-0.5734232 , -0.39805448, -0.678915  , ...,  0.        ,
        -0.53023946,  0.8703399 ],
       [-0.5411381 ,  0.2716505 , -0.9306036 , ..., -0.53023946,
         0.        ,  0.6511102 ],
       [ 0.07277147, -0.6077318 ,  0.5516921 , ...,  0.8703399 ,
         0.6511102 ,  0.        ]], shape=(100, 100), dtype=float32)>